"use client";

import { useAppStore } from "@/store/useAppStore";

const T = {
  vi: {
    // Mobile tabs
    tabCards: "Thẻ",
    tabDay: "Ngày",
    tabMonth: "Tháng",
    tabReport: "Báo cáo",
    // Shared
    expense: "Chi tiêu",
    income: "Thu nhập",
    cancel: "Huỷ",
    saving: "Đang lưu...",
    // CardPanel
    panelTitle: "Thẻ chi tiêu",
    searchPlaceholder: "Tìm thẻ...",
    mobileHintPrefix: "Nhấn + để thêm vào",
    today: "Hôm nay",
    noCards: "Chưa có thẻ nào",
    createFirstCard: "Tạo thẻ đầu tiên",
    noCardsFound: "Không tìm thấy thẻ",
    addNewCard: "Thêm thẻ mới",
    // SelectedDayView
    transactions: "giao dịch",
    dropHover: "Thả thẻ vào đây",
    dropEmpty: "Kéo thẻ chi tiêu vào đây",
    copyYesterday: "Như hôm qua",
    editTxnTitle: "Chỉnh sửa giao dịch?",
    editTxnConfirm: "Tiếp tục chỉnh sửa",
    deleteTxnTitle: "Xóa giao dịch này?",
    deleteTxnSuffix: "sẽ bị xóa vĩnh viễn.",
    deleteTxnConfirm: "Xóa",
    btnTitleEdit: "Chỉnh sửa",
    btnTitleSave: "Lưu thành thẻ mới",
    btnTitleDelete: "Xóa",
    loadingMore: "Đang tải thêm...",
    // ReportView
    reportTitle: (m: number, y: number) => `Báo cáo ${m}/${y}`,
    noReportData: "Chưa có dữ liệu tháng này",
    statAvgDaily: "Chi tiêu TB/ngày",
    statDaysActive: (n: number) => `${n} ngày có chi tiêu`,
    statTopDay: "Ngày nhiều nhất",
    statTotalExpense: "Tổng chi tiêu",
    statTotalIncome: "Tổng thu nhập",
    chartByDay: "Chi tiêu theo ngày",
    chartDayLabel: (d: string | number) => `Ngày ${d}`,
    chartByCat: "Chi tiêu theo danh mục",
    chartBarIncome: "Thu nhập",
    chartBarExpense: "Chi tiêu",
    categoryOther: "Khác",
    // CreateCardDialog
    createCardTitleNew: "Tạo thẻ mới",
    createCardTitleEdit: "Chỉnh sửa thẻ",
    cardNameLabel: "Tên thẻ",
    cardNamePlaceholder: "VD: Ăn sáng, Cà phê, Lương...",
    categoryLabel: "Danh mục",
    addCategoryBtn: "Thêm danh mục",
    amountLabel: "Số tiền",
    defaultHint: "(chọn mặc định ★)",
    addVariantBtn: "Thêm mức giá",
    variantLabelPlaceholder: "Nhãn (tùy chọn)",
    variantAmountPlaceholder: "VD: 25k, 1tr",
    setDefaultTitle: "Đặt làm mặc định",
    amountHintCard: "Nhập số tiền: 25k = 25,000đ · 1.5tr = 1,500,000đ",
    noteOptionalLabel: "Ghi chú (tùy chọn)",
    notePlaceholder: "Ghi chú thêm...",
    cancelBtn: "Hủy",
    createCardBtn: "Tạo thẻ",
    updateCardBtn: "Cập nhật",
    // EditTransactionDialog
    editTxnDialogTitle: "Chỉnh sửa giao dịch",
    txnTitleLabel: "Tên",
    txnAmountLabel: "Số tiền",
    txnAmountPlaceholder: "VD: 35k, 1.5tr",
    txnAmountHint: "25k = 25,000đ · 1.5tr = 1,500,000đ",
    txnNoteLabel: "Ghi chú",
    txnNotePlaceholder: "Ghi chú thêm...",
    saveBtn: "Lưu",
    // CreateCategoryDialog
    createCatTitle: "Thêm danh mục mới",
    catNameLabel: "Tên danh mục",
    catNamePlaceholder: "VD: Ăn sáng, Gym, Lương...",
    catIconLabel: "Biểu tượng",
    catColorLabel: "Màu sắc",
    catPreview: "Xem trước:",
    catFallbackName: "Tên danh mục",
    addCatBtn: "Thêm",
    // SpendingCardItem
    quickAddTitle: "Thêm vào ngày đang chọn",
    dragTitle: "Kéo để thêm vào ngày",
    toastAdded: (title: string) => `Đã thêm "${title}"`,
    toastError: "Thêm thất bại, thử lại",
    deleteCardTitle: "Xóa thẻ này?",
    deleteCardPrefix: "Thẻ",
    deleteCardSuffix: "sẽ bị xóa vĩnh viễn.",
    deleteBtn: "Xóa",
    // DashboardHeader
    logout: "Đăng xuất",
    deleteAccount: "Xoá tài khoản",
    deleteAccountTitle: "Xoá tài khoản?",
    deleteAccountDesc:
      "Tài khoản của bạn sẽ bị đánh dấu chờ xoá. Toàn bộ dữ liệu sẽ bị xoá vĩnh viễn sau 30 ngày.\n\nNếu bạn thay đổi ý định, hãy liên hệ bossxomlut@gmail.com trong vòng 30 ngày để khôi phục.",
    deleteAccountConfirm: "Xoá tài khoản của tôi",
    deleteAccountCancel: "Huỷ",
    deleteAccountError: "Không thể xoá tài khoản. Thử lại sau.",
  },
  en: {
    tabCards: "Cards",
    tabDay: "Day",
    tabMonth: "Month",
    tabReport: "Report",
    expense: "Expense",
    income: "Income",
    cancel: "Cancel",
    saving: "Saving...",
    panelTitle: "Spending cards",
    searchPlaceholder: "Search cards...",
    mobileHintPrefix: "Tap + to add to",
    today: "Today",
    noCards: "No cards yet",
    createFirstCard: "Create first card",
    noCardsFound: "No cards found",
    addNewCard: "Add new card",
    transactions: "transactions",
    dropHover: "Drop card here",
    dropEmpty: "Drag a spending card here",
    copyYesterday: "Copy from yesterday",
    editTxnTitle: "Edit transaction?",
    editTxnConfirm: "Continue editing",
    deleteTxnTitle: "Delete this transaction?",
    deleteTxnSuffix: "will be permanently deleted.",
    deleteTxnConfirm: "Delete",
    btnTitleEdit: "Edit",
    btnTitleSave: "Save as new card",
    btnTitleDelete: "Delete",
    loadingMore: "Loading more...",
    reportTitle: (m: number, y: number) => `Report ${m}/${y}`,
    noReportData: "No data for this month",
    statAvgDaily: "Avg daily spend",
    statDaysActive: (n: number) => `${n} days with spending`,
    statTopDay: "Highest day",
    statTotalExpense: "Total expenses",
    statTotalIncome: "Total income",
    chartByDay: "Spending by day",
    chartDayLabel: (d: string | number) => `Day ${d}`,
    chartByCat: "Spending by category",
    chartBarIncome: "Income",
    chartBarExpense: "Expenses",
    categoryOther: "Other",
    createCardTitleNew: "Create new card",
    createCardTitleEdit: "Edit card",
    cardNameLabel: "Card name",
    cardNamePlaceholder: "E.g. Breakfast, Coffee, Salary...",
    categoryLabel: "Category",
    addCategoryBtn: "Add category",
    amountLabel: "Amount",
    defaultHint: "(set default ★)",
    addVariantBtn: "Add price level",
    variantLabelPlaceholder: "Label (optional)",
    variantAmountPlaceholder: "E.g. 8, 12.5",
    setDefaultTitle: "Set as default",
    amountHintCard: "Enter amount: 8 = $8 · 1,500 = $1,500",
    noteOptionalLabel: "Note (optional)",
    notePlaceholder: "Additional note...",
    cancelBtn: "Cancel",
    createCardBtn: "Create card",
    updateCardBtn: "Update",
    editTxnDialogTitle: "Edit transaction",
    txnTitleLabel: "Title",
    txnAmountLabel: "Amount",
    txnAmountPlaceholder: "E.g. 35, 1500",
    txnAmountHint: "8 = $8 · 1,500 = $1,500",
    txnNoteLabel: "Note",
    txnNotePlaceholder: "Additional note...",
    saveBtn: "Save",
    createCatTitle: "Add new category",
    catNameLabel: "Category name",
    catNamePlaceholder: "E.g. Breakfast, Gym, Salary...",
    catIconLabel: "Icon",
    catColorLabel: "Color",
    catPreview: "Preview:",
    catFallbackName: "Category name",
    addCatBtn: "Add",
    quickAddTitle: "Add to selected date",
    dragTitle: "Drag to add to a date",
    toastAdded: (title: string) => `Added "${title}"`,
    toastError: "Failed to add, please try again",
    deleteCardTitle: "Delete this card?",
    deleteCardPrefix: "Card",
    deleteCardSuffix: "will be permanently deleted.",
    deleteBtn: "Delete",
    logout: "Sign out",
    deleteAccount: "Delete account",
    deleteAccountTitle: "Delete account?",
    deleteAccountDesc:
      "Your account will be marked for deletion. All data will be permanently deleted after 30 days.\n\nIf you change your mind, contact bossxomlut@gmail.com within 30 days to restore your account.",
    deleteAccountConfirm: "Delete my account",
    deleteAccountCancel: "Cancel",
    deleteAccountError: "Could not delete account. Please try again.",
  },
};

export function useDashboardT() {
  const language = useAppStore((s) => s.language);
  return T[language as keyof typeof T] ?? T.vi;
}
