"use client";

import { useAppStore } from "@/store/useAppStore";

const T = {
  vi: {
    // Mobile tabs
    tabCards: "Thẻ",
    tabDay: "Ngày",
    tabMonth: "Tháng",
    tabReport: "Báo cáo",
    // Shared
    expense: "Chi tiêu",
    income: "Thu nhập",
    cancel: "Huỷ",
    saving: "Đang lưu...",
    // CardPanel
    panelTitle: "Thẻ chi tiêu",
    searchPlaceholder: "Tìm thẻ...",
    mobileHintPrefix: "Nhấn + để thêm vào",
    today: "Hôm nay",
    noCards: "Chưa có thẻ nào",
    createFirstCard: "Tạo thẻ đầu tiên",
    noCardsFound: "Không tìm thấy thẻ",
    addNewCard: "Thêm thẻ mới",
    // SelectedDayView
    transactions: "giao dịch",
    dropHover: "Thả thẻ vào đây",
    dropEmpty: "Kéo thẻ chi tiêu vào đây",
    copyYesterday: "Như hôm qua",
    editTxnTitle: "Chỉnh sửa giao dịch?",
    editTxnConfirm: "Tiếp tục chỉnh sửa",
    deleteTxnTitle: "Xóa giao dịch này?",
    deleteTxnSuffix: "sẽ bị xóa vĩnh viễn.",
    deleteTxnConfirm: "Xóa",
    btnTitleEdit: "Chỉnh sửa",
    btnTitleClone: "Nhân bản bên dưới",
    btnTitleSave: "Lưu thành thẻ mới",
    btnTitleDelete: "Xóa",
    loadingMore: "Đang tải thêm...",
    // MonthlyView
    monthSummaryTitle: (m: number, y: number) => `Tổng tháng ${m}/${y}`,
    monthIncome: "Thu nhập",
    monthExpense: "Chi tiêu",
    monthRemaining: "Còn lại",
    monthActiveDays: "Ngày có chi tiêu",
    // ReportView
    reportTitle: (m: number, y: number) => `Báo cáo ${m}/${y}`,
    noReportData: "Chưa có dữ liệu tháng này",
    exportCsv: "Xuất CSV",
    exportCsvFilename: (month: string) => `drag-spend-${month}.csv`,
    csvColDate: "Ngày",
    csvColTitle: "Tiêu đề",
    csvColAmount: "Số tiền",
    csvColType: "Loại",
    csvColCategory: "Danh mục",
    csvColNote: "Ghi chú",
    csvTypeIncome: "Thu nhập",
    csvTypeExpense: "Chi tiêu",
    statAvgDaily: "Chi tiêu TB/ngày",
    statDaysActive: (n: number) => `${n} ngày có chi tiêu`,
    statTopDay: "Ngày nhiều nhất",
    statTotalExpense: "Tổng chi tiêu",
    statTotalIncome: "Tổng thu nhập",
    chartByDay: "Chi tiêu theo ngày",
    chartDayLabel: (d: string | number) => `Ngày ${d}`,
    chartByCat: "Chi tiêu theo danh mục",
    chartBarIncome: "Thu nhập",
    chartBarExpense: "Chi tiêu",
    categoryOther: "Khác",
    catTxTitle: "Giao dịch",
    catTxEmpty: "Không có giao dịch nào",
    // CreateCardDialog
    createCardTitleNew: "Tạo thẻ mới",
    createCardTitleEdit: "Chỉnh sửa thẻ",
    cardNameLabel: "Tên thẻ",
    cardNamePlaceholder: "VD: Ăn sáng, Cà phê, Lương...",
    categoryLabel: "Danh mục",
    addCategoryBtn: "Thêm danh mục",
    amountLabel: "Số tiền",
    defaultHint: "(chọn mặc định ★)",
    addVariantBtn: "Thêm mức giá",
    variantLabelPlaceholder: "Nhãn (tùy chọn)",
    variantAmountPlaceholder: "VD: 25k, 1m",
    setDefaultTitle: "Đặt làm mặc định",
    amountHintCard: "Nhập số tiền: 25k = 25,000đ · 1.5m = 1,500,000đ",
    noteOptionalLabel: "Ghi chú (tùy chọn)",
    notePlaceholder: "Ghi chú thêm...",
    cancelBtn: "Hủy",
    createCardBtn: "Tạo thẻ",
    updateCardBtn: "Cập nhật",
    // EditTransactionDialog
    editTxnDialogTitle: "Chỉnh sửa giao dịch",
    txnTitleLabel: "Tên",
    txnAmountLabel: "Số tiền",
    txnAmountPlaceholder: "VD: 35k, 1.5m",
    txnAmountHint: "25k = 25,000đ · 1.5m = 1,500,000đ",
    txnNoteLabel: "Ghi chú",
    txnNotePlaceholder: "Ghi chú thêm...",
    saveBtn: "Lưu",
    // CreateCategoryDialog
    createCatTitle: "Thêm danh mục mới",
    catNameLabel: "Tên danh mục",
    catNamePlaceholder: "VD: Ăn sáng, Gym, Lương...",
    catIconLabel: "Biểu tượng",
    catColorLabel: "Màu sắc",
    catPreview: "Xem trước:",
    catFallbackName: "Tên danh mục",
    addCatBtn: "Thêm",
    // SpendingCardItem
    quickAddTitle: "Thêm vào ngày đang chọn",
    dragTitle: "Kéo để thêm vào ngày",
    toastAdded: (title: string) => `Đã thêm "${title}"`,
    toastError: "Thêm thất bại, thử lại",
    deleteCardTitle: "Xóa thẻ này?",
    deleteCardPrefix: "Thẻ",
    deleteCardSuffix: "sẽ bị xóa vĩnh viễn.",
    deleteBtn: "Xóa",
    // DashboardHeader
    logout: "Đăng xuất",
    deleteAccount: "Xoá tài khoản",
    deleteAccountTitle: "Xoá tài khoản?",
    deleteAccountDesc:
      "Tài khoản của bạn sẽ bị đánh dấu chờ xoá. Toàn bộ dữ liệu sẽ bị xoá vĩnh viễn sau 30 ngày.\n\nNếu bạn thay đổi ý định, hãy liên hệ bossxomlut@gmail.com trong vòng 30 ngày để khôi phục.",
    deleteAccountConfirm: "Xoá tài khoản của tôi",
    deleteAccountCancel: "Huỷ",
    deleteAccountError: "Không thể xoá tài khoản. Thử lại sau.",
    // TransactionTableView / table mode
    switchToTable: "Chế độ bảng",
    switchToList: "Chế độ danh sách",
    saveChangesBtn: "Lưu thay đổi",
    savingChanges: "Đang lưu...",
    changesSaved: "Đã lưu thay đổi",
    unsavedTitle: "Bỏ thay đổi?",
    unsavedDesc:
      "Bạn có thay đổi chưa được lưu. Bỏ qua và chuyển về danh sách?",
    discardChanges: "Bỏ qua",
    stayEditing: "Tiếp tục chỉnh sửa",
    amountInvalidFormat: "Không đúng định dạng. VD: 25k, 1.5m, 35000",
    titleRequired: "Tên không được để trống",
    // Search
    searchBtn: "Tìm kiếm...",
    searchTitle: "Tìm kiếm giao dịch",
    searchPlaceholderTxn: "Tìm tên giao dịch...",
    filterBtn: "Bộ lọc",
    typeAll: "Tất cả",
    typeExpense: "Chi tiêu",
    typeIncome: "Thu nhập",
    dateFrom: "Từ ngày",
    dateTo: "Đến ngày",
    clearFilter: "Xoá filter",
    searchHint: "Nhập để tìm kiếm giao dịch",
    noResults: "Không tìm thấy kết quả",
    showingOf: (n: number, total: number) => `Hiển thị ${n}/${total} kết quả`,
    viewThisDay: "Xem ngày này",
    statsTitle: "Thống kê kết quả",
    statsCount: (n: number) => `${n} giao dịch`,
    txnDateLabel: "Ngày",
    // Settings
    settingsTitle: "Cài đặt",
    settingsBtn: "Cài đặt",
    settingsProfile: "Hồ sơ",
    settingsDisplayName: "Tên hiển thị",
    settingsDisplayNamePlaceholder: "Tên của bạn",
    settingsSaveName: "Lưu tên",
    settingsNameSaved: "Đã cập nhật tên",
    settingsNameRequired: "Tên không được để trống",
    settingsPassword: "Mật khẩu",
    settingsCurrentPassword: "Mật khẩu hiện tại",
    settingsNewPassword: "Mật khẩu mới",
    settingsConfirmPassword: "Xác nhận mật khẩu mới",
    settingsPasswordPlaceholder: "Tối thiểu 6 ký tự",
    settingsSavePassword: "Đổi mật khẩu",
    settingsPasswordSaved: "Đã đổi mật khẩu thành công",
    settingsPasswordMismatch: "Mật khẩu xác nhận không khớp",
    settingsPasswordTooShort: "Mật khẩu phải có ít nhất 6 ký tự",
    settingsPasswordWrong: "Mật khẩu hiện tại không đúng",
    settingsLanguage: "Ngôn ngữ",
    settingsDangerZone: "Vùng nguy hiểm",
    settingsClose: "Đóng",
    // Budget
    setBudgetBtn: "Ngân sách",
    budgetPlaceholder: "VD: 500k, 2m",
    budgetHint: "Nhập 0 để xoá ngân sách tháng này",
    budgetSaved: "Đã lưu ngân sách",
    removeBudget: "Xoá",
    budgetOf: (spent: string, budget: string) => `${spent} / ${budget}`,
    budgetOver: "Vượt ngân sách!",
    // Recurring
    recurringLabel: "Định kỳ hàng tháng",
    recurringDayLabel: "Vào ngày",
    recurringDayHint: "Tự động nhắc vào ngày này mỗi tháng",
    recurringBanner: (n: number) =>
      `${n} khoản định kỳ chưa được thêm tháng này`,
    recurringOnDay: (day: number) => `ngày ${day}`,
    recurringApplyAll: "Thêm tất cả",
    recurringAddOne: "Thêm",
    recurringApplied: (n: number) => `Đã thêm ${n} khoản định kỳ`,
    recurringNoneLeft: "Tất cả khoản định kỳ đã được thêm",
    recurringBadge: "Định kỳ",
  },
  en: {
    tabCards: "Cards",
    tabDay: "Day",
    tabMonth: "Month",
    tabReport: "Report",
    expense: "Expense",
    income: "Income",
    cancel: "Cancel",
    saving: "Saving...",
    panelTitle: "Spending cards",
    searchPlaceholder: "Search cards...",
    mobileHintPrefix: "Tap + to add to",
    today: "Today",
    noCards: "No cards yet",
    createFirstCard: "Create first card",
    noCardsFound: "No cards found",
    addNewCard: "Add new card",
    transactions: "transactions",
    dropHover: "Drop card here",
    dropEmpty: "Drag a spending card here",
    copyYesterday: "Copy from yesterday",
    editTxnTitle: "Edit transaction?",
    editTxnConfirm: "Continue editing",
    deleteTxnTitle: "Delete this transaction?",
    deleteTxnSuffix: "will be permanently deleted.",
    deleteTxnConfirm: "Delete",
    btnTitleEdit: "Edit",
    btnTitleClone: "Clone below",
    btnTitleSave: "Save as new card",
    btnTitleDelete: "Delete",
    loadingMore: "Loading more...",
    // MonthlyView
    monthSummaryTitle: (m: number, y: number) => `Month ${m}/${y} summary`,
    monthIncome: "Income",
    monthExpense: "Expenses",
    monthRemaining: "Remaining",
    monthActiveDays: "Days with spending",
    // ReportView
    reportTitle: (m: number, y: number) => `Report ${m}/${y}`,
    noReportData: "No data for this month",
    exportCsv: "Export CSV",
    exportCsvFilename: (month: string) => `drag-spend-${month}.csv`,
    csvColDate: "Date",
    csvColTitle: "Title",
    csvColAmount: "Amount",
    csvColType: "Type",
    csvColCategory: "Category",
    csvColNote: "Note",
    csvTypeIncome: "Income",
    csvTypeExpense: "Expense",
    statAvgDaily: "Avg daily spend",
    statDaysActive: (n: number) => `${n} days with spending`,
    statTopDay: "Highest day",
    statTotalExpense: "Total expenses",
    statTotalIncome: "Total income",
    chartByDay: "Spending by day",
    chartDayLabel: (d: string | number) => `Day ${d}`,
    chartByCat: "Spending by category",
    chartBarIncome: "Income",
    chartBarExpense: "Expenses",
    categoryOther: "Other",
    catTxTitle: "Transactions",
    catTxEmpty: "No transactions",
    createCardTitleNew: "Create new card",
    createCardTitleEdit: "Edit card",
    cardNameLabel: "Card name",
    cardNamePlaceholder: "E.g. Breakfast, Coffee, Salary...",
    categoryLabel: "Category",
    addCategoryBtn: "Add category",
    amountLabel: "Amount",
    defaultHint: "(set default ★)",
    addVariantBtn: "Add price level",
    variantLabelPlaceholder: "Label (optional)",
    variantAmountPlaceholder: "E.g. 8, 12.5",
    setDefaultTitle: "Set as default",
    amountHintCard: "Enter amount: 8 = $8 · 1,500 = $1,500",
    noteOptionalLabel: "Note (optional)",
    notePlaceholder: "Additional note...",
    cancelBtn: "Cancel",
    createCardBtn: "Create card",
    updateCardBtn: "Update",
    editTxnDialogTitle: "Edit transaction",
    txnTitleLabel: "Title",
    txnAmountLabel: "Amount",
    txnAmountPlaceholder: "E.g. 35, 1500",
    txnAmountHint: "8 = $8 · 1,500 = $1,500",
    txnNoteLabel: "Note",
    txnNotePlaceholder: "Additional note...",
    saveBtn: "Save",
    createCatTitle: "Add new category",
    catNameLabel: "Category name",
    catNamePlaceholder: "E.g. Breakfast, Gym, Salary...",
    catIconLabel: "Icon",
    catColorLabel: "Color",
    catPreview: "Preview:",
    catFallbackName: "Category name",
    addCatBtn: "Add",
    quickAddTitle: "Add to selected date",
    dragTitle: "Drag to add to a date",
    toastAdded: (title: string) => `Added "${title}"`,
    toastError: "Failed to add, please try again",
    deleteCardTitle: "Delete this card?",
    deleteCardPrefix: "Card",
    deleteCardSuffix: "will be permanently deleted.",
    deleteBtn: "Delete",
    logout: "Sign out",
    deleteAccount: "Delete account",
    deleteAccountTitle: "Delete account?",
    deleteAccountDesc:
      "Your account will be marked for deletion. All data will be permanently deleted after 30 days.\n\nIf you change your mind, contact bossxomlut@gmail.com within 30 days to restore your account.",
    deleteAccountConfirm: "Delete my account",
    deleteAccountCancel: "Cancel",
    deleteAccountError: "Could not delete account. Please try again.",
    // TransactionTableView / table mode
    switchToTable: "Table view",
    switchToList: "List view",
    saveChangesBtn: "Save changes",
    savingChanges: "Saving...",
    changesSaved: "Changes saved",
    unsavedTitle: "Discard changes?",
    unsavedDesc: "You have unsaved changes. Discard and switch to list view?",
    discardChanges: "Discard",
    stayEditing: "Keep editing",
    amountInvalidFormat: "Invalid format. E.g. 25k, 1.5tr, 35000",
    titleRequired: "Title is required",
    // Search
    searchBtn: "Search...",
    searchTitle: "Search transactions",
    searchPlaceholderTxn: "Search transaction name...",
    filterBtn: "Filters",
    typeAll: "All",
    typeExpense: "Expense",
    typeIncome: "Income",
    dateFrom: "From date",
    dateTo: "To date",
    clearFilter: "Clear filters",
    searchHint: "Type to search transactions",
    noResults: "No results found",
    showingOf: (n: number, total: number) => `Showing ${n} of ${total} results`,
    viewThisDay: "View this day",
    statsTitle: "Result statistics",
    statsCount: (n: number) => `${n} transactions`,
    txnDateLabel: "Date",
    // Settings
    settingsTitle: "Settings",
    settingsBtn: "Settings",
    settingsProfile: "Profile",
    settingsDisplayName: "Display name",
    settingsDisplayNamePlaceholder: "Your name",
    settingsSaveName: "Save name",
    settingsNameSaved: "Name updated",
    settingsNameRequired: "Name cannot be empty",
    settingsPassword: "Password",
    settingsCurrentPassword: "Current password",
    settingsNewPassword: "New password",
    settingsConfirmPassword: "Confirm new password",
    settingsPasswordPlaceholder: "At least 6 characters",
    settingsSavePassword: "Change password",
    settingsPasswordSaved: "Password changed successfully",
    settingsPasswordMismatch: "Passwords do not match",
    settingsPasswordTooShort: "Password must be at least 6 characters",
    settingsPasswordWrong: "Current password is incorrect",
    settingsLanguage: "Language",
    settingsDangerZone: "Danger zone",
    settingsClose: "Close",
    // Budget
    setBudgetBtn: "Budget",
    budgetPlaceholder: "E.g. 500k, 2m",
    budgetHint: "Enter 0 to remove this month's budget",
    budgetSaved: "Budget saved",
    removeBudget: "Remove",
    budgetOf: (spent: string, budget: string) => `${spent} / ${budget}`,
    budgetOver: "Over budget!",
    // Recurring
    recurringLabel: "Monthly recurring",
    recurringDayLabel: "On day",
    recurringDayHint: "Auto-remind on this day each month",
    recurringBanner: (n: number) =>
      `${n} recurring item${n === 1 ? "" : "s"} not yet added this month`,
    recurringOnDay: (day: number) => `day ${day}`,
    recurringApplyAll: "Add all",
    recurringAddOne: "Add",
    recurringApplied: (n: number) =>
      `Added ${n} recurring item${n === 1 ? "" : "s"}`,
    recurringNoneLeft: "All recurring items already added",
    recurringBadge: "Recurring",
  },
};

export function useDashboardT() {
  const language = useAppStore((s) => s.language);
  return T[language as keyof typeof T] ?? T.vi;
}
